 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/github_issues", type: :request do
  # GithubIssue. As you add validations to GithubIssue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GithubIssue.create! valid_attributes
      get github_issues_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      github_issue = GithubIssue.create! valid_attributes
      get github_issue_url(github_issue)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_github_issue_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      github_issue = GithubIssue.create! valid_attributes
      get edit_github_issue_url(github_issue)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GithubIssue" do
        expect {
          post github_issues_url, params: { github_issue: valid_attributes }
        }.to change(GithubIssue, :count).by(1)
      end

      it "redirects to the created github_issue" do
        post github_issues_url, params: { github_issue: valid_attributes }
        expect(response).to redirect_to(github_issue_url(GithubIssue.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GithubIssue" do
        expect {
          post github_issues_url, params: { github_issue: invalid_attributes }
        }.to change(GithubIssue, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post github_issues_url, params: { github_issue: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested github_issue" do
        github_issue = GithubIssue.create! valid_attributes
        patch github_issue_url(github_issue), params: { github_issue: new_attributes }
        github_issue.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the github_issue" do
        github_issue = GithubIssue.create! valid_attributes
        patch github_issue_url(github_issue), params: { github_issue: new_attributes }
        github_issue.reload
        expect(response).to redirect_to(github_issue_url(github_issue))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        github_issue = GithubIssue.create! valid_attributes
        patch github_issue_url(github_issue), params: { github_issue: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested github_issue" do
      github_issue = GithubIssue.create! valid_attributes
      expect {
        delete github_issue_url(github_issue)
      }.to change(GithubIssue, :count).by(-1)
    end

    it "redirects to the github_issues list" do
      github_issue = GithubIssue.create! valid_attributes
      delete github_issue_url(github_issue)
      expect(response).to redirect_to(github_issues_url)
    end
  end
end
